# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  networking.hostName = "macbook-pro";

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.kernelParams = [ "resume_offset=97652736" "pcie_ports=native" ];
  boot.extraModulePackages = [ ];
  services.hardware.bolt.enable = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/dc0b49c3-bee6-424c-bbad-8fc61ae9b7ee";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5F66-17ED";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # needed for hibernate
  swapDevices = [{
    device = "/var/lib/swapfile";
    size = 64*1024; # 16 GiB
  }];
  boot.resumeDevice = "/dev/disk/by-uuid/dc0b49c3-bee6-424c-bbad-8fc61ae9b7ee";
  powerManagement.enable = true;


  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # hardware.firmware = [
  #   (pkgs.stdenvNoCC.mkDerivation (final: {
  #     name = "brcm-firmware";
  #     src = ../../../private/firmware/brcm;
  #     installPhase = ''
  #       mkdir -p $out/lib/firmware/brcm
  #       cp ${final.src}/* "$out/lib/firmware/brcm"
  #     '';
  #   }))
  # ];

  hardware.apple-t2 = {
    enableIGPU = true;
    firmware.enable = true;
  };

  services.t2fanrd = {
    enable = true;
    config.Fan1 = {
      low_temp = 50;
      high_temp = 80;
      speed_curve = "exponential";
    };
    config.Fan2 = {
      low_temp = 50;
      high_temp = 80;
      speed_curve = "exponential";
    };
  };

}
