# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "virtio_pci" "xhci_pci" "usbhid" "usb_storage" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/14fa584b-bab4-4a99-b12a-0c1441932943";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7835-D92C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/share" = {
     device = "share";
     fsType = "virtiofs";
     options = [
       "nofail"
       "x-systemd.automount"
     ];
   };

  swapDevices = [ ];

  networking.hostName = "macvm";
  virtualisation.rosetta.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
