filetype plugin on
syntax on
filetype plugin indent on
set ttyfast
set number
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set splitright
set autoindent
set nowrap
set nocompatible 
set modeline

" au BufRead,BufNewFile *.agda call AgdaFiletype()
" au BufWritePost *.agda execute "normal! :CornelisLoad\<CR>"
" au QuitPre *.agda :CornelisCloseInfoWindows
" function! AgdaFiletype()
"     nnoremap <buffer> <C-c><C-l> :CornelisLoad<CR>
"     nnoremap <buffer> <C-c><C-r> :CornelisRefine<CR>
"     nnoremap <buffer> <C-c><C-g> :CornelisGive<CR>
"     nnoremap <buffer> <C-c><C-c> :CornelisMakeCase<CR>
"     nnoremap <buffer> <C-c><C-,> :CornelisTypeContext Simplified<CR>
"     nnoremap <buffer> <C-c><C-.> :CornelisTypeContextInfer<CR>
"     nnoremap <buffer> <C-c><C-s> :CornelisSolve<CR>
"     nnoremap <buffer> <C-c><C-a> :CornelisAuto<CR>
"     nnoremap <buffer> <C-c><C-?> :CornelisQuestionToMeta<CR>
"     nnoremap <buffer> gd         :CornelisGoToDefinition<CR>
"     nnoremap <buffer> <C-c><C-b> :CornelisPrevGoal<CR>
"     nnoremap <buffer> <C-c><C-f> :CornelisNextGoal<CR>
"     nnoremap <buffer> <C-A>     :CornelisInc<CR>
"     nnoremap <buffer> <C-X>     :CornelisDec<CR>
" 
"       " Highlight holes with a yellow undercurl/underline:
"     highlight CornelisHole ctermfg=yellow ctermbg=NONE cterm=undercurl
" 
"     " Highlight "generalizables" (declarations in `variable` blocks) like constants:
"     highlight link CornelisGeneralizable Constant
" endfunction

imap <C-p> <Up>
imap <C-n> <Down>
imap <C-b> <Left>
imap <C-f> <Right>
imap <C-a> <C-o>:call <SID>home()<CR>
imap <C-e> <End>
imap <C-d> <Del>
imap <C-h> <BS>
imap <C-k> <C-r>=<SID>kill()<CR>

function! s:home()
  let start_column = col('.')
  normal! ^
  if col('.') == start_column
    normal! 0
  endif
  return ''
endfunction

function! s:kill()
  let [text_before, text_after] = s:split_line()
  if len(text_after) == 0
    normal! J
  else
    call setline(line('.'), text_before)
  endif
  return ''
endfunction

function! s:split_line()
  let line_text = getline(line('.'))
  let text_after  = line_text[col('.')-1 :]
  let text_before = (col('.') > 1) ? line_text[: col('.')-2] : ''
  return [text_before, text_after]
endfunction
