#!/run/current-system/sw/bin/bash
# Program Vars

#if [[ -z $(ls /Library/Fonts/Nix\ Fonts | grep 'sketchybar-app-font') ]]; then
#  echo 'Sketchybarfont not found…'
#  killall sketchybar
#fi

RELPATH="$(dirname "$0")"
export PATH=/opt/homebrew/bin:/opt/homebrew/sbin:$PATH
mkdir -p ${TMPDIR}sketchybar


if [[ $DEV_MODE == true ]]; then source "$RELPATH/colors.sh"; fi
if [[ $DEV_MODE == true ]]; then source "$RELPATH/icon_map.sh"; fi
if [[ $DEV_MODE == true ]]; then source "$RELPATH/add_separator.sh"; fi

# Multi Purpose Property vars

FONT="SF Pro"
OUTER_PADDINGS=5
INNER_PADDINGS=5
X_BAR_PADDING=12
BAR_HEIGHT=34

# --- Bar & Default Properties ---

bar=(
  height=$BAR_HEIGHT
  y_offset=4
  margin=5
  shadow=on
  shadow.color=$TEXT_MOON
  padding_left=0
  padding_right=$X_BAR_PADDING
  color=$BAR_COLOR
  border_width=1
  border_color=$BORDER_COLOR
  corner_radius=14
  blur_radius=40
  notch_width=180
)

defaults=(
  updates=when_shown
  icon.font="$FONT:Regular:14.0"
  icon.color=$ICON_COLOR
  padding_left=$OUTER_PADDINGS
  padding_right=$OUTER_PADDINGS
  icon.padding_left=$INNER_PADDINGS
  icon.padding_right=$INNER_PADDINGS
  label.font="$FONT:Semibold:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=$INNER_PADDINGS
  label.padding_right=$INNER_PADDINGS
  background.corner_radius=8
  popup.y_offset=4
  popup.background.border_width=1
  popup.background.corner_radius=6
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)

zones=(
  background.height=$(($BAR_HEIGHT - 8))
  background.border_width=2
  background.border_color=$HIGH_MED_MOON
  background.color=$OVERLAY_MOON
  background.corner_radius=8
  blur_radius=24
)

sketchybar --bar "${bar[@]}"
sketchybar --default "${defaults[@]}"

# --- Bar Items ---

if [[ $DEV_MODE == true ]]; then source "$RELPATH/sketchy-items/logo.sh"; fi
if [[ $DEV_MODE == true ]]; then source "$RELPATH/sketchy-items/spaces.sh"; fi
if [[ $DEV_MODE == true ]]; then source "$RELPATH/sketchy-items/frontapp.sh"; fi
if [[ $DEV_MODE == true ]]; then source "$RELPATH/sketchy-items/menus.sh"; fi
if [[ $DEV_MODE == true ]]; then source "$RELPATH/sketchy-items/calendar.sh"; fi
if [[ $DEV_MODE == true ]]; then source "$RELPATH/sketchy-items/mic.sh"; fi
if [[ $DEV_MODE == true ]]; then source "$RELPATH/sketchy-items/volume.sh"; fi
if [[ $DEV_MODE == true ]]; then source "$RELPATH/sketchy-items/battery.sh"; fi
if [[ $DEV_MODE == true ]]; then source "$RELPATH/sketchy-items/wifi.sh"; fi
if [[ $DEV_MODE == true ]]; then source "$RELPATH/sketchy-items/display.sh"; fi
if [[ $DEV_MODE == true ]]; then source "$RELPATH/sketchy-items/more-menu.sh"; fi
if [[ $DEV_MODE == true ]]; then source "$RELPATH/sketchy-items/packages.sh"; fi
if [[ $DEV_MODE == true ]]; then source "$RELPATH/sketchy-items/controls.sh"; fi

if [[ $DEV_MODE == true ]]; then source "$RELPATH/sketchy-items/music.sh"; fi
if [[ $DEV_MODE == true ]]; then source "$RELPATH/sketchy-items/cpu.sh"; fi

if [[ $DEV_MODE == true ]]; then source "$RELPATH/sketchyset.sh"; fi
